# Generated by Django 5.2.4 on 2025-07-21 11:58

from django.db import migrations

def create_initial_restaurants(apps, schema_editor):
    Restaurant = apps.get_model('api', 'Restaurant')
    Restaurant.objects.create(name='The Pizza Palace', address='123 Main St', phone_number='555-1234')
    Restaurant.objects.create(name='Burger Barn', address='456 Oak Ave', phone_number='555-5678')
    Restaurant.objects.create(name='Taco Town', address='789 Pine Ln', phone_number='555-9012')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_restaurants),
    ]
