# Generated by Django 5.2.1 on 2025-07-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_customer_lat_order_customer_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=255),
        ),
    ]
