# Generated by Django 5.2.1 on 2025-07-25 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_menuitem_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_breakfast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_dinner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_lunch',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='api.modifiergroup')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='modifier_groups',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='api.modifiergroup'),
        ),
    ]
