# Generated by Django 5.2.4 on 2025-08-02 09:37

from django.db import migrations

# This is the correct dependency. Django will automatically find the last migration in the app.
# If you have a specific dependency, you would list it here.
# In our case, the previous migration in 'api' is the one we depend on.

def forwards_func(apps, schema_editor):
    # This data migration has been intentionally disabled because it depended on
    # the deleted 'restaurant_onboarding' app. The data has been manually reconciled.
    pass

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        # This should point to the last valid migration before the failed one.
        # Based on the file list, '0017_notification' seems to be the last one, but the name was garbled.
        # Let's trust the migration that was generated before: '0018_alter_menucategory_options_and_more'
        # Since we deleted 0019, the new 0019 will depend on the *next* one to be created.
        # Let's set the dependency to the last known good migration.
        ('api', '0017_notification'), 

    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]

