# Generated by Django 5.2.4 on 2025-08-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_data_migrate_menucategory_restaurants'),
        ('api', '0022_alter_order_status'),
    ]

    operations = [
    ]
