# Generated by Django 5.2.4 on 2025-08-07 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_device_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'token')},
        ),
    ]
