# Generated by Django 5.2.4 on 2025-08-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_device_updated_at_alter_device_device_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('INFORMATIONAL', 'Informational'), ('REMINDER', 'Reminder'), ('PROMOTIONAL', 'Promotional'), ('PERSONALIZED', 'Personalized'), ('TRANSACTIONAL', 'Transactional'), ('ENGAGEMENT', 'Engagement')], max_length=20)),
                ('name', models.CharField(help_text="A unique name for internal reference, e.g., 'promo_flash_sale'", max_length=100, unique=True)),
                ('title', models.CharField(help_text='The notification title, can include emojis.', max_length=255)),
                ('body', models.TextField(help_text='The main content of the notification.')),
                ('image_url', models.URLField(blank=True, help_text='Optional URL for a rich notification image.', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
