# Generated by Django 5.2.4 on 2025-08-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_orderreview_riderreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
