# Generated by Django 4.2.7 on 2025-08-25 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0033_riderprofile_rating_riderprofile_rating_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='riderreview',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='riderreview',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='rating_count',
        ),
        migrations.AddField(
            model_name='order',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.riderprofile'),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riderreview',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='riderreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='riderreview',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_received', to='api.riderprofile'),
        ),
        migrations.AlterField(
            model_name='riderreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_rider_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.order')),
            ],
            options={
                'verbose_name_plural': 'Order Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The total amount of the bill.', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='api.restaurant')),
            ],
        ),
    ]
