# Generated by Django 5.2.4 on 2025-08-23 15:50

from django.db import migrations


def cleanup_orphan_orders(apps, schema_editor):
    """
    Finds Order objects with a rider_id that points to a non-existent
    RiderProfile and sets the rider_id to NULL.
    """
    Order = apps.get_model('api', 'Order')
    RiderProfile = apps.get_model('api', 'RiderProfile')

    # Get a list of all existing rider IDs
    existing_rider_ids = set(RiderProfile.objects.values_list('id', flat=True))

    # Find orders that have a rider_id that is not in the existing rider list
    # We exclude orders where rider_id is already NULL
    orphan_orders = Order.objects.exclude(rider_id__in=existing_rider_ids).exclude(rider_id__isnull=True)

    # Set the rider_id to NULL for these orphan orders
    # This is a safe operation as the field allows NULL values
    updated_count = orphan_orders.update(rider=None)

    if updated_count > 0:
        print(f'\nCleaned up {updated_count} orphan Order records.')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20250810_0959'),
    ]

    operations = [
        migrations.RunPython(cleanup_orphan_orders, migrations.RunPython.noop),
    ]
