# Generated by Django 5.2.4 on 2025-08-10 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_menuitem_average_rating_menuitem_review_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='riderreview',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='riderreview',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='rating_count',
        ),
        migrations.AlterField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.riderprofile'),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riderreview',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='riderreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='riderreview',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='api.riderprofile'),
        ),
        migrations.AlterField(
            model_name='riderreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_rider_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
