# Generated by Django 4.2.7 on 2025-09-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_orderpayment_paymentperiod_paymentdispute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_prep_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('dine_in', 'Dine-in')], default='delivery', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Preparing', 'Preparing'), ('Ready for Pickup', 'Ready for Pickup'), ('Ready for Dine-in', 'Ready for Dine-in'), ('Assigned', 'Assigned'), ('Out for Delivery', 'Out for Delivery'), ('Rider Arrived', 'Rider Arrived'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
