# Generated by Django 5.2.4 on 2025-08-10 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_orderreview_options_alter_riderreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderreview',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_received', to='api.riderprofile'),
        ),
    ]
