# Generated by Django 5.2.4 on 2025-09-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_add_dine_in_fields'),
        ('api', '0036_order_estimated_prep_time_order_order_type_and_more'),
    ]

    operations = [
    ]
