# Generated by Django 4.2.7 on 2025-08-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
