# Generated by Django 4.2.7 on 2025-09-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_merge_20250902_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_prep_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('dine_in', 'Dine-in')], default='delivery', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Preparing', 'Preparing'), ('Ready for Pickup', 'Ready for Pickup'), ('Ready for Dine-in', 'Ready for Dine-in'), ('Assigned', 'Assigned'), ('Out for Delivery', 'Out for Delivery'), ('Rider Arrived', 'Rider Arrived'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
