# Generated by Django 5.2.4 on 2025-08-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_orderreview_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreview',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
