# Generated by Django 5.2.4 on 2025-08-10 18:10

from django.db import migrations


from django.db import migrations

def backfill_restaurant_in_reviews(apps, schema_editor):
    OrderReview = apps.get_model('api', 'OrderReview')
    for review in OrderReview.objects.filter(restaurant__isnull=True).iterator():
        if review.order:
            review.restaurant = review.order.restaurant
            review.save(update_fields=['restaurant'])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_orderreview_replied_at_orderreview_reply_text'),
    ]

    operations = [
        migrations.RunPython(backfill_restaurant_in_reviews, migrations.RunPython.noop),
    ]
