# Generated by Django 4.2.7 on 2025-10-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pesapal_tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
