# Generated by Django 4.2.7 on 2025-10-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_payment_pesapal_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('mtn_mobile_money', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('pesapal', 'Pesapal'), ('pesapal_mtn', 'PesaPal MTN Mobile Money'), ('pesapal_airtel', 'PesaPal Airtel Money')], default='cash_on_delivery', max_length=20),
        ),
    ]
