# Generated by Django 5.2.4 on 2025-08-23 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_menuitem_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.order')),
            ],
            options={
                'verbose_name_plural': 'Order Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
