# Generated by Django 4.2.7 on 2025-10-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdispute',
            old_name='resolution_notes',
            new_name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='paymentdispute',
            name='restaurant_response',
        ),
        migrations.AddField(
            model_name='payment',
            name='mtn_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentdispute',
            name='mtn_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentdispute',
            name='pesapal_tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
