// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCddAXJDCrXuIMvLb5PmouXbvCh7HaEIz4',
    appId: '1:1094257727094:web:84b0ddcf92a3dde035f157',
    messagingSenderId: '1094257727094',
    projectId: 'fortexpress-5641c',
    authDomain: 'fortexpress-5641c.firebaseapp.com',
    storageBucket: 'fortexpress-5641c.firebasestorage.app',
    measurementId: 'G-5K8CHN1VPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZCsX_zwQr3jB9XdByRX4Si2kjZVFQCCY',
    appId: '1:1094257727094:android:8c59955f7cd18a3035f157',
    messagingSenderId: '1094257727094',
    projectId: 'fortexpress-5641c',
    storageBucket: 'fortexpress-5641c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGcWbkEJUj0VCd0aDBntlIX_cIfQQKeks',
    appId: '1:1094257727094:ios:81e15566e04d7a2b35f157',
    messagingSenderId: '1094257727094',
    projectId: 'fortexpress-5641c',
    storageBucket: 'fortexpress-5641c.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGcWbkEJUj0VCd0aDBntlIX_cIfQQKeks',
    appId: '1:1094257727094:ios:81e15566e04d7a2b35f157',
    messagingSenderId: '1094257727094',
    projectId: 'fortexpress-5641c',
    storageBucket: 'fortexpress-5641c.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
