databases:
  - name: fooddeliverydb
    plan: free
    databaseName: fooddelivery
    user: fooddelivery

services:
  - type: redis
    name: food-delivery-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
  - type: web
    name: food-delivery-backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
        fromDatabase:
          name: fooddeliverydb
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: food-delivery-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: RENDER
        value: true
      - key: GOOGLE_MAPS_API_KEY
        value: AIzaSyB2_rwYdL9Tr_LWV7PDfn83n8-2_6KVahs
      - key: GOOGLE_CLOUD_PROJECT
        value: fortexpress-5641c
