# Generated by Django 5.2.4 on 2025-08-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_onboarding', '0002_alter_restaurant_address_alter_restaurant_owner_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='order_protocol',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('EMAIL', 'Email'), ('PHONE', 'Phone Call')], default='TABLET', max_length=10),
        ),
    ]
