# Generated by Django 5.2.4 on 2025-08-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_onboarding', '0003_restaurant_order_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
