# Generated by Django 5.2.4 on 2025-08-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_onboarding', '0004_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
